# Generated by Django 5.2.7 on 2025-11-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_boarduserpermission_delete_boardaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='state',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
